version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php/:/var/www/html/
      - ./ssl/:/etc/nginx/ssl/
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    restart: unless-stopped